import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { ThemeConfig } from '@/themes';
import { Blueprint } from '@/store';

export const exportThemePackage = async (theme: ThemeConfig) => {
  const zip = new JSZip();
  const themeFolder = zip.folder("theme");
  
  if (!themeFolder) return;

  // 1. theme.json
  const themeJson = {
    $schema: "https://valtrexui.com/schema/theme/v1.json",
    ...theme
  };
  themeFolder.file("theme.json", JSON.stringify(themeJson, null, 2));

  // 2. colors.json
  themeFolder.file("colors.json", JSON.stringify(theme.colors, null, 2));

  // 3. typography.json
  themeFolder.file("typography.json", JSON.stringify(theme.typography, null, 2));

  // 4. spacing.json
  themeFolder.file("spacing.json", JSON.stringify(theme.spacing, null, 2));

  // 5. theme.css (CSS variables)
  const cssVars = `
:root {
  --color-primary: ${theme.colors.primary};
  --color-secondary: ${theme.colors.secondary};
  --color-background: ${theme.colors.background};
  --color-surface: ${theme.colors.surface};
  --color-text-primary: ${theme.colors.textPrimary};
  --color-text-secondary: ${theme.colors.textSecondary};
  --color-text-muted: ${theme.colors.textMuted};
  --color-border: ${theme.colors.border};
  
  --color-accent-blue: ${theme.colors.accents.blue};
  --color-accent-pink: ${theme.colors.accents.pink};
  ${theme.colors.accents.green ? `--color-accent-green: ${theme.colors.accents.green};` : ''}

  --font-family: ${theme.typography.fontFamily};
  
  --shadow-sm: ${theme.shadows.sm};
  --shadow-md: ${theme.shadows.md};
  --shadow-lg: ${theme.shadows.lg};
  --glow-shadow: ${theme.shadows.glow};

  --radius-sm: ${theme.borderRadius.sm};
  --radius-md: ${theme.borderRadius.md};
  --radius-lg: ${theme.borderRadius.lg};
}
`;
  themeFolder.file("theme.css", cssVars);

  // 6. tailwind-preset.ts (v4 compatible setup conceptually)
  const tailwindPreset = `
import type { Config } from 'tailwindcss';

export const valtrexThemePreset = {
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        secondary: "var(--color-secondary)",
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        textPrimary: "var(--color-text-primary)",
        textSecondary: "var(--color-text-secondary)",
        textMuted: "var(--color-text-muted)",
        border: "var(--color-border)",
        accentBlue: "var(--color-accent-blue)",
        accentPink: "var(--color-accent-pink)",
      },
      fontFamily: {
        sans: ["var(--font-family)"],
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        glow: "var(--glow-shadow)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
      }
    }
  }
} satisfies Partial<Config>;
`;
  themeFolder.file("tailwind-preset.ts", tailwindPreset);

  // 7. README.md
  themeFolder.file("README.md", `# ${theme.metadata.name}
  
Generated by ValtrexUI.
This package contains the design tokens for ${theme.metadata.name}.
Include \`theme.css\` in your global styles and use \`tailwind-preset.ts\` in your Tailwind configuration.`);

  // Generate and download
  const content = await zip.generateAsync({ type: "blob" });
  saveAs(content, `${theme.id}-package.zip`);
};

export const exportUIPackage = async (blueprint: Blueprint, theme: ThemeConfig) => {
  const zip = new JSZip();
  const src = zip.folder("src");
  if (!src) return;

  const components = src.folder("components");
  const layouts = src.folder("layouts");
  const pages = src.folder("pages");
  const themeFolder = src.folder("theme");

  themeFolder?.file("theme.json", JSON.stringify(theme, null, 2));

  blueprint.pages.forEach(page => {
    pages?.file(`${page}.tsx`, `
import React from 'react';
import { PageLayout } from '../layouts/PageLayout';

export default function ${page}() {
  return (
    <PageLayout title="${page}">
      <div className="p-8">
        <h1 className="text-3xl font-bold text-textPrimary">${page}</h1>
        {/* Generated content for ${page} based on ${blueprint.projectName} */}
      </div>
    </PageLayout>
  );
}
`);
  });

  layouts?.file("PageLayout.tsx", `
import React from 'react';
export function PageLayout({ children, title }: { children: React.ReactNode, title: string }) {
  return (
    <div className="min-h-screen bg-background text-textPrimary">
      <nav className="border-b border-border p-4 bg-surface">
         <span className="font-bold">${blueprint.projectName} - {title}</span>
      </nav>
      <main>{children}</main>
    </div>
  );
}
`);

  // Generate and download
  const content = await zip.generateAsync({ type: "blob" });
  saveAs(content, `${blueprint.projectName.toLowerCase().replace(/\\s+/g, '-')}-ui-package.zip`);
};
